version: '3'
services:
  db:
    image: postgres:14.4
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - '.:/app'
      - bundle:/usr/local/bundle
    ports:
      - '3000:3000'
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file: app.env
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '10'

volumes:
  postgres:
  bundle:
